# This is an example .meta-cnc.yaml file. This will allow Panhandler to consume this terraform project

# this is the name of this skillet, should be unique within a given repository
name: retail_pos

# label should be a human readable label that conveys what this skillet will do
label: Point of Sale (POS) recommended config

# description is a longer more informative version of a label
description: POS security policies and profiles for retail

# type instructs Panhandler how to consume this skillet
type: panos

# extends allows you to include other skillets along with this one
extends:

# labels allow extensible configuration options per skillet type. For example, lables can be used to
# group multiple skillets of the same type (pan-os skillets labeled as version: 9.0 for example)
labels:
  collection:
    - Configure
    - Retail
    - POS
    - Best Practice


# Variables will be presented to the user via the Panhandler GUI. These values will then be passed to
# the terraform binary as '--var' options, thus overriding any tfvars entries.
# Variable names MUST match the names of the defined terraform variables
variables:

