# This is an example .meta-cnc.yaml file. This will allow Panhandler to consume this terraform project

# this is the name of this skillet, should be unique within a given repository
name: kvm_single_pavm_no_bootstrap

# label should be a human readable label that conveys what this skillet will do
label: KVM Single PAN-OS VM-Series

# description is a longer more informative version of a label
description: KVM Single PAN-OS VM-Series

# type instructs Panhandler how to consume this skillet
type: terraform

# extends allows you to include other skillets along with this one
extends:

# labels allow extensible configuration options per skillet type. For example, lables can be used to
# group multiple skillets of the same type (pan-os skillets labeled as version: 9.0 for example)
labels:
  terraform_provider: kvm
  collection:
    - Private Cloud
    - Deploy
    - KVM


# Variables will be presented to the user via the Panhandler GUI. These values will then be passed to
# the terraform binary as '--var' options, thus overriding any tfvars entries.
# Variable names MUST match the names of the defined terraform variables
variables:
  - name: access_key
    description: KVM Access Key
    default: access_key
    type_hint: text
  - name: secret_key
    description: KVM Secret Key
    default:
    type_hint: password
  - name: pavm_key_name
    description: SSH Key Name
    default: ssh_key_pair
    type_hint: text
  - name: region
    description: KVM Region
    default: us-east-2
    type_hint: text
  - name: availability_zone
    description: KVM Availability Zone
    default: us-east-2b
    type_hint: text

