# This is an example .meta-cnc.yaml file. This will allow Panhandler to consume this terraform project

# this is the name of this skillet, should be unique within a given repository
name: cloud_security_framework_aws

# label should be a human readable label that conveys what this skillet will do
label: AWS Cloud Security Framework - Step 1

# description is a longer more informative version of a label
description: Demonstrate advantages of NGFW in Public Cloud

# type instructs Panhandler how to consume this skillet
type: template

# extends allows you to include other skillets along with this one
extends:

# labels allow extensible configuration options per skillet type. For example, lables can be used to
# group multiple skillets of the same type (pan-os skillets labeled as version: 9.0 for example)
labels:
  collection:
    - Demonstrate
    - Public Cloud
    - AWS


# Variables will be presented to the user via the Panhandler GUI. These values will then be passed to
# the terraform binary as '--var' options, thus overriding any tfvars entries.
# Variable names MUST match the names of the defined terraform variables
variables:

